name:                aoc
version:             0.1.0.0
github:              "githubuser/aoc"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/githubuser/aoc#readme>

dependencies:
- base >= 4.7 && < 5
- mtl >= 2.2.2
- containers >= 0.6.7
- split
- text
- array
- linear

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wmissing-home-modules
- -Wpartial-fields
- -Wno-incomplete-patterns 
- -Wno-incomplete-uni-patterns 

executables:
  aoc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
